/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author User
 */
public class CreateInsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInsuranceJPanel
     */
    Product product;
    public CreateInsuranceJPanel(Product product) {
        initComponents();
        this.product=product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyName = new javax.swing.JLabel();
        lblCorporateid = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductable = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtCorporateid = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtDeductable = new javax.swing.JTextField();
        btnSaveInsurance = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        lblCompanyName.setForeground(new java.awt.Color(0, 102, 51));
        lblCompanyName.setText("Company Name:");

        lblCorporateid.setForeground(new java.awt.Color(0, 102, 51));
        lblCorporateid.setText("Corporate ID:");

        lblPremium.setForeground(new java.awt.Color(0, 102, 51));
        lblPremium.setText("Premium:");

        lblDeductable.setForeground(new java.awt.Color(0, 102, 51));
        lblDeductable.setText("Deductable:");

        txtCompanyName.setBackground(new java.awt.Color(51, 255, 255));

        txtCorporateid.setBackground(new java.awt.Color(51, 255, 255));

        txtPremium.setBackground(new java.awt.Color(51, 255, 255));

        txtDeductable.setBackground(new java.awt.Color(51, 255, 255));
        txtDeductable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeductableActionPerformed(evt);
            }
        });

        btnSaveInsurance.setBackground(new java.awt.Color(0, 255, 0));
        btnSaveInsurance.setText("Save");
        btnSaveInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInsuranceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompanyName)
                            .addComponent(lblCorporateid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPremium, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeductable, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnSaveInsurance)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyName)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateid)
                    .addComponent(txtCorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveInsurance)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInsuranceActionPerformed
        // TODO add your handling code here:
        product.setCompanyname(txtCompanyName.getText());
        product.setCorporateid(txtCorporateid.getText());
        product.setPremium(txtPremium.getText());
        product.setDeductable(txtDeductable.getText());
        
        JOptionPane.showMessageDialog(this,"Information Saved");
    }//GEN-LAST:event_btnSaveInsuranceActionPerformed

    private void txtDeductableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeductableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeductableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveInsurance;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCorporateid;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCorporateid;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtPremium;
    // End of variables declaration//GEN-END:variables
}
