/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author User
 */
public class CreateDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctorJPanel
     */
    Product product;
    public CreateDoctorJPanel(Product product) {
        initComponents();
        this.product=product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorName = new javax.swing.JLabel();
        lblDoctorid = new javax.swing.JLabel();
        lblSpecialisation = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        txtDoctorid = new javax.swing.JTextField();
        txtSpecialisation = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        btnSaveDoctor = new javax.swing.JButton();
        lblGraduationCollege = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtGraduationCollege = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        lblDoctorName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDoctorName.setForeground(new java.awt.Color(255, 0, 51));
        lblDoctorName.setText("Doctor Name:");

        lblDoctorid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDoctorid.setForeground(new java.awt.Color(255, 0, 51));
        lblDoctorid.setText("Doctor ID:");

        lblSpecialisation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSpecialisation.setForeground(new java.awt.Color(255, 0, 51));
        lblSpecialisation.setText("Specialisation:");

        lblExperience.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblExperience.setForeground(new java.awt.Color(255, 0, 51));
        lblExperience.setText("Experience:");

        lblNationality.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNationality.setForeground(new java.awt.Color(255, 0, 51));
        lblNationality.setText("Nationality:");

        txtDoctorName.setBackground(new java.awt.Color(204, 255, 255));

        txtDoctorid.setBackground(new java.awt.Color(204, 255, 255));

        txtSpecialisation.setBackground(new java.awt.Color(204, 255, 255));

        txtExperience.setBackground(new java.awt.Color(204, 255, 255));

        txtNationality.setBackground(new java.awt.Color(204, 255, 255));

        btnSaveDoctor.setBackground(new java.awt.Color(0, 204, 204));
        btnSaveDoctor.setText("Save");
        btnSaveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDoctorActionPerformed(evt);
            }
        });

        lblGraduationCollege.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGraduationCollege.setForeground(new java.awt.Color(255, 0, 51));
        lblGraduationCollege.setText("Graduation College:");

        lblGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 0, 51));
        lblGender.setText("Gender:");

        txtGender.setBackground(new java.awt.Color(204, 255, 255));

        txtGraduationCollege.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNationality)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblExperience)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSpecialisation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDoctorName)
                            .addGap(50, 50, 50)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDoctorid)
                                .addComponent(lblGender))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDoctorid, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(txtGender))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGraduationCollege)
                        .addGap(18, 18, 18)
                        .addComponent(txtGraduationCollege)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnSaveDoctor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorName)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorid)
                    .addComponent(txtDoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExperience)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNationality)
                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraduationCollege)
                    .addComponent(txtGraduationCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialisation)
                    .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveDoctor)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDoctorActionPerformed
        // TODO add your handling code here:
        product.setDoctorname(txtDoctorName.getText());
        product.setDoctorid(txtDoctorid.getText());
        product.setSpecialisation(txtSpecialisation.getText());
        product.setExperience(txtExperience.getText());
        product.setNationality(txtNationality.getText());
        product.setGender(txtGender.getText());
        product.setGraduationcollege(txtGraduationCollege.getText());
        
        JOptionPane.showMessageDialog(this,"Information Saved");
    }//GEN-LAST:event_btnSaveDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDoctor;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDoctorid;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGraduationCollege;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblSpecialisation;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorid;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtGraduationCollege;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtSpecialisation;
    // End of variables declaration//GEN-END:variables
}
