/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Product;

/**
 *
 * @author User
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Product product;
    public MainJFrame() {
        initComponents();
        product=new Product();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnCreateDriver = new javax.swing.JButton();
        btnCreateRegistration = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnDisplayReport = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnCreateInsurance = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        controlPanel.setBackground(new java.awt.Color(0, 255, 255));

        btnCreatePerson.setBackground(new java.awt.Color(255, 0, 0));
        btnCreatePerson.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreatePerson.setText("Enter Person Details");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnCreateDriver.setBackground(new java.awt.Color(255, 0, 0));
        btnCreateDriver.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreateDriver.setText("Enter Driver Details");
        btnCreateDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDriverActionPerformed(evt);
            }
        });

        btnCreateRegistration.setBackground(new java.awt.Color(255, 0, 0));
        btnCreateRegistration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreateRegistration.setText("Vehicle Registration");
        btnCreateRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRegistrationActionPerformed(evt);
            }
        });

        btnCreatePatient.setBackground(new java.awt.Color(255, 0, 0));
        btnCreatePatient.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreatePatient.setText("Patient Details");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnDisplayReport.setBackground(new java.awt.Color(0, 102, 102));
        btnDisplayReport.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDisplayReport.setText("Display Report");
        btnDisplayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayReportActionPerformed(evt);
            }
        });

        btnCreateDoctor.setBackground(new java.awt.Color(255, 0, 0));
        btnCreateDoctor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreateDoctor.setText("Doctor Details");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnCreateInsurance.setBackground(new java.awt.Color(255, 0, 0));
        btnCreateInsurance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCreateInsurance.setText("Insurance Details");
        btnCreateInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInsuranceActionPerformed(evt);
            }
        });

        btnAddress.setBackground(new java.awt.Color(255, 0, 0));
        btnAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddress.setText("Enter Address");
        btnAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateInsurance)
                    .addComponent(btnCreateDoctor)
                    .addComponent(btnDisplayReport)
                    .addComponent(btnCreatePatient)
                    .addComponent(btnAddress)
                    .addComponent(btnCreatePerson)
                    .addComponent(btnCreateRegistration)
                    .addComponent(btnCreateDriver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplayReport)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createpersonPanel=new CreatePersonJPanel(product);
        splitPane.setRightComponent(createpersonPanel);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreateDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDriverActionPerformed
        // TODO add your handling code here:
        CreateDriverJPanel createdriverpanel=new CreateDriverJPanel(product);
        splitPane.setRightComponent(createdriverpanel);
    }//GEN-LAST:event_btnCreateDriverActionPerformed

    private void btnCreateRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRegistrationActionPerformed
        // TODO add your handling code here:
        CreateRegistrationJPanel createregistrationpanel= new CreateRegistrationJPanel(product);
        splitPane.setRightComponent(createregistrationpanel);
    }//GEN-LAST:event_btnCreateRegistrationActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel patientpanel=new CreatePatientJPanel(product);
        splitPane.setRightComponent(patientpanel);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        CreateDoctorJPanel doctorpanel=new CreateDoctorJPanel(product);
        splitPane.setRightComponent(doctorpanel);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddressActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel addresspanel= new CreateAddressJPanel(product);
        splitPane.setRightComponent(addresspanel);
    }//GEN-LAST:event_btnAddressActionPerformed

    private void btnCreateInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInsuranceActionPerformed
        // TODO add your handling code here:
        CreateInsuranceJPanel insurancepanel=new CreateInsuranceJPanel(product);
        splitPane.setRightComponent(insurancepanel);
    }//GEN-LAST:event_btnCreateInsuranceActionPerformed

    private void display(){
        System.out.println("Name:" +product.getName());
        System.out.println("Age:" +product.getAge());
        System.out.println("phone number:" +product.getPhonenumber());
        System.out.println("Email:" +product.getEmail());
        System.out.println("SSN:" +product.getSsn());
        System.out.println("Employment Status:" +product.getEmployementstatus());
        System.out.println("Website:" +product.getWebsite());
        System.out.println("Social Media Handle:" +product.getSocialmedia());
        System.out.println("Date of Birth:" +product.getDateofbirth());
        System.out.println("Blood Group:" +product.getBloodgroup());
        System.out.println("Driver Name:" +product.getDrivername());
        System.out.println("License Number:" +product.getLicensenumber());
        System.out.println("Driver Age:" +product.getDriverage());
        System.out.println("Car Model:" +product.getCarmodel());
        System.out.println("Serial Number:" +product.getSerialnumber());
        System.out.println("Patient Name:" +product.getPatientname());
        System.out.println("Patient ID:" +product.getPatientid());
        System.out.println("Primary Doctor:" +product.getPrimarydoctor());
        System.out.println("Date of Visit:" +product.getDateoflastvisit());
        System.out.println("Next Date of Visit:" +product.getNextdateofvisit());
        System.out.println("Reason for Visit:" +product.getReasonforvisit());
        System.out.println("Treatment:" +product.getTreatmentundergoing());
        System.out.println("Doctor Name:" +product.getDoctorname());
        System.out.println("Doctor ID:" +product.getDoctorid());
        System.out.println("Experience:" +product.getExperience());
        System.out.println("Specialisation:" +product.getSpecialisation());
        System.out.println("Nationality:" +product.getNationality());
        System.out.println("Gender:" +product.getGender());
        System.out.println("Graduation College:" +product.getGraduationcollege());
        System.out.println("Company Name:" +product.getCompanyname());
        System.out.println("Corporate ID:" +product.getCorporateid());
        System.out.println("Premium:" +product.getPremium());
        System.out.println("Deductable:" +product.getDeductable());
        System.out.println("GPS Location:" +product.getGpslocation());
        System.out.println("City:" +product.getCity());
        System.out.println("State:" +product.getState());
        System.out.println("Country:" +product.getCountry());
    
    }
    private void btnDisplayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayReportActionPerformed
        // TODO add your handling code here:
        RecordJPanel patientpanel=new RecordJPanel(product);
        splitPane.setRightComponent(patientpanel);
        display();
                
    }//GEN-LAST:event_btnDisplayReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateDriver;
    private javax.swing.JButton btnCreateInsurance;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnCreateRegistration;
    private javax.swing.JButton btnDisplayReport;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
