/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import model.Product;

/**
 *
 * @author User
 */
public class RecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordJPanel
     */
    Product product;
    public RecordJPanel(Product product) {
        initComponents();
        this.product=product;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTreatment = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtDoctorid = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        lblDoctorName = new javax.swing.JLabel();
        txtDateOfLastVisit = new javax.swing.JTextField();
        lblDoctorid = new javax.swing.JLabel();
        txtDateOfNextVisit = new javax.swing.JTextField();
        lblPrimaryDoctor = new javax.swing.JLabel();
        txtReasonForVisit = new javax.swing.JTextField();
        txtTreatmentUndergone = new javax.swing.JTextField();
        lblDateofLastVisit = new javax.swing.JLabel();
        lblNextDateofVisit = new javax.swing.JLabel();
        lblReasonForVisit = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientid = new javax.swing.JTextField();
        lblPatientName = new javax.swing.JLabel();
        lblPatientid = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        txtSpecialisation = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        txtGraduationCollege = new javax.swing.JTextField();
        lblSpecialisation = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        lblGraduationCollege = new javax.swing.JLabel();
        lblDateofBirth = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        lblSocialMedia = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblEmploymentstatus = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        lblWebsite = new javax.swing.JLabel();
        txtEmployment = new javax.swing.JTextField();
        txtDateofBirth = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        txtSocialMedia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblGPSLocation = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        txtGPSLocation = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblDriverName = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblDriverAge = new javax.swing.JLabel();
        txtDriverName = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtDriverAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductable = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtCorporateid = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtDeductable = new javax.swing.JTextField();
        lblCompanyName = new javax.swing.JLabel();
        lblCorporateid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCarModel = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        lblTreatment.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTreatment.setText("Treatment Undergone:");

        txtGender.setBackground(new java.awt.Color(204, 255, 255));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtDoctorid.setBackground(new java.awt.Color(204, 255, 255));
        txtDoctorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctoridActionPerformed(evt);
            }
        });

        txtPrimaryDoctor.setBackground(new java.awt.Color(204, 255, 255));
        txtPrimaryDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryDoctorActionPerformed(evt);
            }
        });

        lblDoctorName.setText("Doctor Name:");

        txtDateOfLastVisit.setBackground(new java.awt.Color(204, 255, 255));
        txtDateOfLastVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfLastVisitActionPerformed(evt);
            }
        });

        lblDoctorid.setText("Doctor ID:");

        txtDateOfNextVisit.setBackground(new java.awt.Color(204, 255, 255));
        txtDateOfNextVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfNextVisitActionPerformed(evt);
            }
        });

        lblPrimaryDoctor.setText("Primary Doctor:");

        txtReasonForVisit.setBackground(new java.awt.Color(204, 255, 255));
        txtReasonForVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReasonForVisitActionPerformed(evt);
            }
        });

        txtTreatmentUndergone.setBackground(new java.awt.Color(204, 255, 255));
        txtTreatmentUndergone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreatmentUndergoneActionPerformed(evt);
            }
        });

        lblDateofLastVisit.setText("Date of Last Visit:");

        lblNextDateofVisit.setText("Date of Next Visit:");

        lblReasonForVisit.setText("Reason for Visit:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Record");

        txtPatientName.setBackground(new java.awt.Color(204, 255, 255));

        txtPatientid.setBackground(new java.awt.Color(204, 255, 255));

        lblPatientName.setText("Patient Name:");

        lblPatientid.setText("Patient ID:");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle1.setText("Doctor Details");

        txtSpecialisation.setBackground(new java.awt.Color(204, 255, 255));

        txtExperience.setBackground(new java.awt.Color(204, 255, 255));
        txtExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienceActionPerformed(evt);
            }
        });

        txtNationality.setBackground(new java.awt.Color(204, 255, 255));
        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        lblGender.setText("Gender:");

        txtDoctorName.setBackground(new java.awt.Color(204, 255, 255));
        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });

        txtGraduationCollege.setBackground(new java.awt.Color(204, 255, 255));

        lblSpecialisation.setText("Specialisation:");

        lblExperience.setText("Experience:");

        lblNationality.setText("Nationality:");

        lblGraduationCollege.setText("Graduation College:");

        lblDateofBirth.setText("Date of Birth:");

        lblBloodGroup.setText("Blood Group:");

        lblSocialMedia.setText("Social Media:");

        lblName.setText("Name:");

        txtName.setBackground(new java.awt.Color(0, 255, 255));

        lblAge.setText("Age:");

        txtAge.setBackground(new java.awt.Color(0, 255, 255));

        lblEmail.setText("Email:");

        txtPhone.setBackground(new java.awt.Color(0, 255, 255));

        lblPhoneNumber1.setText("Phone:");

        txtEmail.setBackground(new java.awt.Color(0, 255, 255));

        lblSSN.setText("SSN:");

        txtSSN.setBackground(new java.awt.Color(0, 255, 255));

        lblEmploymentstatus.setText("Employment Status:");

        txtWebsite.setBackground(new java.awt.Color(0, 255, 255));

        lblWebsite.setText("website:");

        txtEmployment.setBackground(new java.awt.Color(0, 255, 255));

        txtDateofBirth.setBackground(new java.awt.Color(0, 255, 255));

        txtBloodGroup.setBackground(new java.awt.Color(0, 255, 255));

        txtSocialMedia.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Personal Details");

        lblGPSLocation.setText("GPS Location:");

        lblState.setText("State:");

        lblCity.setText("City:");

        lblCountry.setText("Country:");

        txtGPSLocation.setBackground(new java.awt.Color(204, 255, 204));

        txtState.setBackground(new java.awt.Color(204, 255, 204));

        txtCity.setBackground(new java.awt.Color(204, 255, 204));

        txtCountry.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Address");

        lblDriverName.setText("Driver Name:");

        lblLicenseNumber.setText("License Number:");

        lblDriverAge.setText("Driver Age:");

        txtDriverName.setBackground(new java.awt.Color(204, 255, 204));
        txtDriverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverNameActionPerformed(evt);
            }
        });

        txtLicenseNumber.setBackground(new java.awt.Color(204, 255, 204));
        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });

        txtDriverAge.setBackground(new java.awt.Color(204, 255, 204));
        txtDriverAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverAgeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Driver Details");

        lblPremium.setText("Premium:");

        lblDeductable.setText("Deductable:");

        txtCompanyName.setBackground(new java.awt.Color(51, 255, 255));

        txtCorporateid.setBackground(new java.awt.Color(51, 255, 255));

        txtPremium.setBackground(new java.awt.Color(51, 255, 255));

        txtDeductable.setBackground(new java.awt.Color(51, 255, 255));
        txtDeductable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeductableActionPerformed(evt);
            }
        });

        lblCompanyName.setText("Company Name:");

        lblCorporateid.setText("Corporate ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Insurance Details");

        lblCarModel.setText("Model:");

        lblSerialNumber.setText("Serial No:");

        txtModel.setBackground(new java.awt.Color(0, 255, 255));
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtSerialNumber.setBackground(new java.awt.Color(0, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Vehicle Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientid)
                                    .addComponent(lblPatientName)))
                            .addComponent(lblPrimaryDoctor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNextDateofVisit)
                            .addComponent(lblDateofLastVisit)
                            .addComponent(lblReasonForVisit)
                            .addComponent(lblTreatment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDateOfNextVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatmentUndergone, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompanyName)
                            .addComponent(lblCorporateid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPremium, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeductable, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail)
                            .addComponent(lblPhoneNumber1)
                            .addComponent(lblSSN)
                            .addComponent(lblEmploymentstatus)
                            .addComponent(lblWebsite)
                            .addComponent(lblDateofBirth)
                            .addComponent(lblBloodGroup)
                            .addComponent(lblSocialMedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(219, 219, 219))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLicenseNumber)
                                    .addComponent(lblDriverName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDriverAge, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDriverAge, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(133, 133, 133)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblState)
                                    .addComponent(lblGPSLocation)
                                    .addComponent(lblCity)
                                    .addComponent(lblCountry))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGPSLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGraduationCollege)
                                        .addComponent(lblExperience, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNationality, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtGraduationCollege)
                                        .addComponent(txtNationality)
                                        .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDoctorName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblDoctorid, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(15, 15, 15)
                                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtDoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(3, 3, 3))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(111, 111, 111)
                                    .addComponent(lblSpecialisation)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblTitle1)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDoctorName)
                                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDoctorid)
                                    .addComponent(txtDoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblExperience)
                                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNationality)
                                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGraduationCollege)
                                    .addComponent(txtGraduationCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSpecialisation)
                                    .addComponent(txtSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGPSLocation)
                                    .addComponent(txtGPSLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblState)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCountry)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPatientName))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPatientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(lblPatientid)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrimaryDoctor)
                                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDateofLastVisit)
                                    .addComponent(txtDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDateOfNextVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNextDateofVisit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReasonForVisit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTreatmentUndergone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhoneNumber1)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSSN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmploymentstatus))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWebsite))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDateofBirth))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBloodGroup))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSocialMedia)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDriverName)
                                    .addComponent(txtDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicenseNumber)
                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDriverAge)
                                    .addComponent(txtDriverAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompanyName)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorporateid)
                            .addComponent(txtCorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPremium)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarModel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNumber)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(453, 453, 453))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDoctoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctoridActionPerformed

    private void txtPrimaryDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryDoctorActionPerformed

    private void txtDateOfLastVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfLastVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfLastVisitActionPerformed

    private void txtDateOfNextVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfNextVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfNextVisitActionPerformed

    private void txtReasonForVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReasonForVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReasonForVisitActionPerformed

    private void txtTreatmentUndergoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatmentUndergoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreatmentUndergoneActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtDriverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverNameActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtDriverAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverAgeActionPerformed

    private void txtDeductableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeductableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeductableActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCorporateid;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblDateofLastVisit;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDoctorid;
    private javax.swing.JLabel lblDriverAge;
    private javax.swing.JLabel lblDriverName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmploymentstatus;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblGPSLocation;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGraduationCollege;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblNextDateofVisit;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientid;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblReasonForVisit;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSocialMedia;
    private javax.swing.JLabel lblSpecialisation;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCorporateid;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDateOfLastVisit;
    private javax.swing.JTextField txtDateOfNextVisit;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtDoctorid;
    private javax.swing.JTextField txtDriverAge;
    private javax.swing.JTextField txtDriverName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployment;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtGPSLocation;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtGraduationCollege;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientid;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtPrimaryDoctor;
    private javax.swing.JTextField txtReasonForVisit;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtSocialMedia;
    private javax.swing.JTextField txtSpecialisation;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTreatmentUndergone;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        txtGender.setText(product.getPatientname());
        txtDoctorid.setText(product.getPatientid());
        txtDateOfLastVisit.setText(product.getDateoflastvisit());
        txtDateOfNextVisit.setText(product.getNextdateofvisit());
        txtReasonForVisit.setText(product.getReasonforvisit());
        txtTreatmentUndergone.setText(product.getTreatmentundergoing());
        txtPrimaryDoctor.setText(product.getPrimarydoctor());
        txtName.setText(product.getName());
        txtAge.setText(product.getAge());
        txtEmail.setText(product.getEmail());
        txtPhone.setText(product.getPhonenumber());
        txtSSN.setText(product.getSsn());
        txtBloodGroup.setText(product.getBloodgroup());
        txtDateofBirth.setText(product.getDateofbirth());
        txtWebsite.setText(product.getWebsite());
        txtSocialMedia.setText(product.getSocialmedia());
        txtSSN.setText(product.getSsn());
        txtEmployment.setText(product.getEmployementstatus());
        txtPatientName.setText(product.getPatientname());
        txtPatientid.setText(product.getPatientid());
        txtPrimaryDoctor.setText(product.getPrimarydoctor());
        txtDateOfLastVisit.setText(product.getDateoflastvisit());
        txtDateOfNextVisit.setText(product.getNextdateofvisit());
        txtReasonForVisit.setText(product.getReasonforvisit());
        txtTreatmentUndergone.setText(product.getTreatmentundergoing());
        txtDoctorName.setText(product.getDoctorname());
        txtDoctorid.setText(product.getDoctorid());
        txtGender.setText(product.getGender());
        txtSpecialisation.setText(product.getSpecialisation());
        txtExperience.setText(product.getExperience());
        txtNationality.setText(product.getNationality());
        txtGraduationCollege.setText(product.getGraduationcollege());
        txtGPSLocation.setText(product.getGpslocation());
        txtCity.setText(product.getCity());
        txtCountry.setText(product.getCountry());
        txtState.setText(product.getState());
        txtDriverName.setText(product.getDrivername());
        txtDriverAge.setText(product.getDriverage());
        txtLicenseNumber.setText(product.getLicensenumber());
        txtCompanyName.setText(product.getCompanyname());
        txtPremium.setText(product.getPremium());
        txtDeductable.setText(product.getDeductable());
        txtCorporateid.setText(product.getCorporateid());
        txtModel.setText(product.getCarmodel());
        txtSerialNumber.setText(product.getSerialnumber());
        
    }}
    /**
     *
     * @param args
     */
    /* public static void main(String[]args)
    {
    Scanner myscanner= new Scanner(System.in);
    }
    }*/





